/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasIndexRouteImport } from './routes/obras.index'
import { Route as ObrasIdRouteImport } from './routes/obras.$id'
import { Route as ObrasIdIndexRouteImport } from './routes/obras.$id.index'
import { Route as ObrasIdApartamentosAptIdRouteImport } from './routes/obras.$id.apartamentos.$aptId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIndexRoute = ObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdRoute = ObrasIdRouteImport.update({
  id: '/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdIndexRoute = ObrasIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObrasIdRoute,
} as any)
const ObrasIdApartamentosAptIdRoute =
  ObrasIdApartamentosAptIdRouteImport.update({
    id: '/apartamentos/$aptId',
    path: '/apartamentos/$aptId',
    getParentRoute: () => ObrasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/obras/$id': typeof ObrasIdRouteWithChildren
  '/obras/': typeof ObrasIndexRoute
  '/obras/$id/': typeof ObrasIdIndexRoute
  '/obras/$id/apartamentos/$aptId': typeof ObrasIdApartamentosAptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/obras': typeof ObrasIndexRoute
  '/obras/$id': typeof ObrasIdIndexRoute
  '/obras/$id/apartamentos/$aptId': typeof ObrasIdApartamentosAptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/obras/$id': typeof ObrasIdRouteWithChildren
  '/obras/': typeof ObrasIndexRoute
  '/obras/$id/': typeof ObrasIdIndexRoute
  '/obras/$id/apartamentos/$aptId': typeof ObrasIdApartamentosAptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/obras/$id'
    | '/obras/'
    | '/obras/$id/'
    | '/obras/$id/apartamentos/$aptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/obras'
    | '/obras/$id'
    | '/obras/$id/apartamentos/$aptId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reset-password'
    | '/obras/$id'
    | '/obras/'
    | '/obras/$id/'
    | '/obras/$id/apartamentos/$aptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ObrasIdRoute: typeof ObrasIdRouteWithChildren
  ObrasIndexRoute: typeof ObrasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/': {
      id: '/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof ObrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id': {
      id: '/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof ObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id/': {
      id: '/obras/$id/'
      path: '/'
      fullPath: '/obras/$id/'
      preLoaderRoute: typeof ObrasIdIndexRouteImport
      parentRoute: typeof ObrasIdRoute
    }
    '/obras/$id/apartamentos/$aptId': {
      id: '/obras/$id/apartamentos/$aptId'
      path: '/apartamentos/$aptId'
      fullPath: '/obras/$id/apartamentos/$aptId'
      preLoaderRoute: typeof ObrasIdApartamentosAptIdRouteImport
      parentRoute: typeof ObrasIdRoute
    }
  }
}

interface ObrasIdRouteChildren {
  ObrasIdIndexRoute: typeof ObrasIdIndexRoute
  ObrasIdApartamentosAptIdRoute: typeof ObrasIdApartamentosAptIdRoute
}

const ObrasIdRouteChildren: ObrasIdRouteChildren = {
  ObrasIdIndexRoute: ObrasIdIndexRoute,
  ObrasIdApartamentosAptIdRoute: ObrasIdApartamentosAptIdRoute,
}

const ObrasIdRouteWithChildren =
  ObrasIdRoute._addFileChildren(ObrasIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ObrasIdRoute: ObrasIdRouteWithChildren,
  ObrasIndexRoute: ObrasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
