/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasIndexRouteImport } from './routes/obras.index'
import { Route as ObrasIdIndexRouteImport } from './routes/obras.$id.index'
import { Route as ObrasIdApartamentosAptIdRouteImport } from './routes/obras.$id.apartamentos.$aptId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIndexRoute = ObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdIndexRoute = ObrasIdIndexRouteImport.update({
  id: '/obras/$id/',
  path: '/obras/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdApartamentosAptIdRoute =
  ObrasIdApartamentosAptIdRouteImport.update({
    id: '/apartamentos/$aptId',
    path: '/apartamentos/$aptId',
    getParentRoute: () => ObrasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/obras/': typeof ObrasIndexRoute
  '/obras/$id/': typeof ObrasIdIndexRoute
  '/obras/$id/apartamentos/$aptId': typeof ObrasIdApartamentosAptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasIndexRoute
  '/obras/$id': typeof ObrasIdIndexRoute
  '/obras/$id/apartamentos/$aptId': typeof ObrasIdApartamentosAptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/obras/': typeof ObrasIndexRoute
  '/obras/$id/': typeof ObrasIdIndexRoute
  '/obras/$id/apartamentos/$aptId': typeof ObrasIdApartamentosAptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/obras/'
    | '/obras/$id/'
    | '/obras/$id/apartamentos/$aptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/obras'
    | '/obras/$id'
    | '/obras/$id/apartamentos/$aptId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/obras/'
    | '/obras/$id/'
    | '/obras/$id/apartamentos/$aptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ObrasIndexRoute: typeof ObrasIndexRoute
  ObrasIdIndexRoute: typeof ObrasIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/': {
      id: '/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof ObrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id/': {
      id: '/obras/$id/'
      path: '/obras/$id'
      fullPath: '/obras/$id/'
      preLoaderRoute: typeof ObrasIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id/apartamentos/$aptId': {
      id: '/obras/$id/apartamentos/$aptId'
      path: '/apartamentos/$aptId'
      fullPath: '/obras/$id/apartamentos/$aptId'
      preLoaderRoute: typeof ObrasIdApartamentosAptIdRouteImport
      parentRoute: typeof ObrasIdRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ObrasIndexRoute: ObrasIndexRoute,
  ObrasIdIndexRoute: ObrasIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
